version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
workflows:
  build:
    jobs:
      - build-and-test
      - cypress/run
